version: 2
updates:
- package-ecosystem: github-actions
  directory: "/pruettiijohn@gmail.com"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
  reviewers:
  - Zachwylde00
  assignees:
  - zachwylde00
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
